
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

input_text:
  og_category_change:
    name: OG Category Change
    max: 255

shell_command:
  update_og_categories: "python3 /config/scripts/og_categories.py"
  og_set_category: "python3 /config/scripts/og_set_category.py '{{ states(\"input_text.og_category_change\") }}'"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
